### ISSUE TITLE
REST API documentation error, consistency, and issue tracking

### ISSUE THREAD

**Issue by amarinelli** [AmrEldib/agol-schemas#15]
Tracking inconsistencies and errors found at: http://resources.arcgis.com/en/help/arcgis-rest-api/

> _This comment will be updated as required_
- [ ] [Item](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Item/02r30000007w000000/)
  - [ ] `guid` is listed in JSON Response Syntax/Example but not in the Response Properties table
- [ ] [Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Group/02r30000006m000000/)
  - [ ] Response Properties missing `"isReadOnly"`, `"capabilities"`, `"provider"`, and `"providerGroupName"` which are returned in a [sample response](http://ontarioregion.maps.arcgis.com/sharing/rest/community/groups/401d8533ae9849cc87f5a07a0f6399ac?f=pjson) from ArcGIS Online.
    - _`provider` property likely related to new [social logins](http://doc.arcgis.com/en/arcgis-online/reference/create-account.htm#ESRI_SECTION1_7963DBC5F1814034A33E796FAFF0BD7F)_.
  - [ ] JSON Response Example missing quotes around `"thumbnail"` property `streets.jpg`.
  - [ ] JSON Response Example missing quotations and comma for `public` in `"access"` property.
  - Included in `BUG-000095573: Some discrepancies between what the rest endpoint shows and what is listed in the samples of the documentation have been discovered`
- [ ] [Group Search](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Group_Search/02r3000000m1000000/)
  - [ ] JSON Response Syntax is missing quotations surrounding `file name` of `"thumbnail"` property.
  - [ ] JSON Response Example shows an email address in the `"phone"` property.
  - Included in `BUG-000095573: Some discrepancies between what the rest endpoint shows and what is listed in the samples of the documentation have been discovered`
- [ ] [Delete Info](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Info/02r3000002nm000000/)
  - [ ] Missing Response Properties table
