### ISSUE TITLE
TODO: priority schemas for ArcGIS Online functionality

### ISSUE THREAD

**Issue by amarinelli** [AmrEldib/agol-schemas#18]
**Community**
- [x] [Invite to Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Invite_to_Group/02r30000006v000000/)
- [x] [Join Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Join_Group/02r30000006n000000/)
- [x] [Leave Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Leave_Group/02r30000006z000000/)
- [x] [Reassign Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Reassign_Group/02r300000067000000/)
- [x] [Remove Users From Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Remove_Users_From_Group/02r300000066000000/)
- [x] [Self (Community)](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Self/02r300000079000000/)
- [x] [Update Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Update_Group/02r30000006w000000/)

**Content**
- [x] [Add Comment](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Comment/02r300000090000000/)  
- [x] [Add Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Item/02r30000008q000000/)  
- [x] [Add Item Part](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Item_Part/02r300000094000000/)  
- [x] [Add Rating](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Rating/02r30000007v000000/)
- [x] [Create Folder](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Create_Folder/02r300000074000000/)
- [x] [Create Service](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Create_Service/02r30000027r000000/)
- [x] [Delete Comment](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Comment/02r300000072000000/)
- [x] [Delete Folder](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Folder/02r30000008m000000/)
- [x] [Delete Info](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Info/02r3000002nm000000/)
- [x] [Delete Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Item/02r300000092000000/)
- [x] [Delete Items](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Items/02r30000008r000000/)
- [x] [Delete Rating](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Rating/02r30000008p000000/)
- [x] [Export Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Export_Item/02r30000008s000000/)
- [ ] [Item Data](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Item_Data/02r300000075000000/)
- [ ] [Move Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Move_Item/02r300000078000000/)
- [ ] [Move Items](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Move_Items/02r30000008v000000/)
- [ ] [Publish Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Publish_Item/02r300000080000000/)
- [ ] [Protect](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Protect/02r300000269000000/)
- [ ] [Reassign Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Reassign_Item/02r300000097000000/)
- [ ] [Share Item (as item owner)](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Share_Item_as_item_owner/02r30000007s000000/)  
- [ ] [Share Item (as group admin)](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Share_Item_as_group_admin/02r3000001m5000000/)  
- [ ] [Share Items](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Share_Items/02r30000008z000000/)  
- [ ] [Status](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Status/02r300000089000000/)  
- [ ] [Unprotect](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Unprotect/02r30000026n000000/)  
- [ ] [Unshare Item (as item owner)](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Unshare_Item_as_item_owner/02r30000007t000000/)  
- [ ] [Unshare Item (as group admin)](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Unshare_Item_as_group_admin/02r3000001mn000000/)  
- [ ] [Unshare Items](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Unshare_Items/02r300000096000000/)  
- [ ] [Update Comment](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Update_Comment/02r300000086000000/)  
- [ ] [Update Info](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Update_Info/02r3000001mm000000/)  
- [ ] [Update Item](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Update_Item/02r30000009s000000/)

**Portals**
- [ ] [Add Resource](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Resource/02r300000082000000/)  
- [ ] [Check Service Name](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Check_Service_Name/02r300000076000000/)
- [ ] [Remove Resource](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Remove_Resource/02r300000073000000/)  
- [ ] [Remove Users](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Remove_Users/02r30000008n000000/)
- [ ] [Update User Role](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Update_User_Role/02r30000007z000000/)

**OAuth 2.0** 
- [ ] [Authorize](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Authorize/02r300000214000000/)
- [ ] [Register App](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Register_App/02r30000026q000000/)
- [ ] [Registered App](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Registered_App/02r30000026v000000/)
- [ ] [Token](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Token/02r300000213000000/)

**Comment by AmrEldib** [comment]
@amarinelli I'd like to add some common data types [Geometry](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Geometry_objects/02r3000000n1000000/) and [Webmap](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Web_map_format/02r30000004n000000/)
Geometry will be very helpful if we split it into its own tool that generates and validates geometry JSON. This will be helpful in testing.
Webmap will be needed when working with those.
